name: Deploy Beta

on:
  workflow_dispatch:

env:
  GIT_BRANCH: ${{ github.ref_name }}
  PROJECT_NAME: telegram-bot-front
  PROJECT_DIR: /home/ec2-user/telegram-bot
  SSH_HOST: ${{ vars.BETA_SSH_HOST }}
  SSH_USER: ec2-user
  SSH_KEY: ${{ secrets.BETA_SSH_KEY }}
  ENV_FRONT: ${{ secrets.BETA_ENV_FRONT }}
  ENV_BACK: ${{ secrets.BETA_ENV_BACK }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        envs: ENV_BACK
        script_stop: true
        script: |
          cd ${{ env.PROJECT_DIR}}/${{ env.PROJECT_NAME }}
          git fetch --all
          git reset --hard origin/${{ env.GIT_BRANCH }}

          echo "${ENV_FRONT}" > .env
          echo "${ENV_BACK}" > backend/.env

          docker system prune -f
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml stop
          docker-compose -f docker-compose.yml up -d
